language: node_js
node_js:
  - '16'
services:
  - mongodb
cache: yarn
branches:
  only:
    - main
env:
  global:
    - PORT=9000
    - MONGODB_URL=mongodb://localhost:27017/node-boilerplate
    - JWT_SECRET=thisisasamplesecret
script:
  - yarn lint
  - yarn test
  - yarn test:e2e
after_success: yarn test:coverage
