language: node_js
node_js:
  - "16"
services:
  - mongodb
cache: yarn
branches:
  only:
    - main
env:
  global:
    - APP_PORT=9000
    - DB_SERVER=mongodb://localhost:27017/
    - DB_NAME=core
    - JWT_SECRET=somerandomkeyherena
script:
  - yarn test
  - yarn test:e2e
after_success: yarn coverage:coveralls
